name: Trigger workflow_run to update labels to PR on new comment and review activity
# this trigger workflow_run on .github/workflows/pr-chages-requested-label-workflow-run.yml
# in this way the GITHUB_TOKEN that's used by workflow_run will have PR write access
on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
jobs:
  create-artifact-for-workflow_run:
    uses: ./.github/workflows/create-artifact-for-workflow_run.yml
