name: Check that every PR meets requirement
on:
  pull_request:
    branches: [master]
jobs:
  pr-incoming-head-must-have-success-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: ./.github/workflows/scripts/pr-requirements/pr-incoming-head-must-have-success-run.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
